/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Dienthoai;
import controller.GioihanException;
import controller.IOFile;
import controller.TrongException;
import controller.TrungException;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BangDangKy;
import model.MonHoc;
import model.SinhVien;

/**
 *
 * @author Phuc
 */
public class Main extends javax.swing.JFrame {

    DefaultTableModel tmMH, tmSV, tmBDK;
    String fMH, fSV, fBDK;
    List<MonHoc> listMH;
    List<SinhVien> listSV;
    List<BangDangKy> listBDK;
    boolean them, sua, them2, sua2, them3;

    public Main() {
        initComponents();
        fMH = "src/controller/MonHoc.dat";
        fSV = "src/controller/SinhVien.dat";
        fBDK = "src/controller/BangDangKy.dat";
        String[] mh = {"Ma Mon hoc", "Ten Mon Hoc", "So Tiet", "Loai"};
        String[] SV = {"Ma Sinh Vien", "Ten Sinh Vien", "Dia chi", "Dien thoai"};
        String[] bDK = {"Ma Sinh Vien", "Ten Sinh Vien", "Ma Mon hoc", "Ten Mon hoc", "Thoi gian dang ky"};
        tmMH = new DefaultTableModel(mh, 0);
        jTable1.setModel(tmMH);
        tmSV = new DefaultTableModel(SV, 0);
        jTable2.setModel(tmSV);
        tmBDK = new DefaultTableModel(bDK, 0);
        jTable3.setModel(tmBDK);
        loadMH();
        loadSV();
        loadBDK();
        showMH(listMH);
        showSV(listSV);
        showBDK(listBDK);
        ButtonState1(true);
        ButtonState2(true);
        ButtonState3(true);
        them = false;
        sua = false;
        them2 = false;
        sua2 = false;
    }

    private void loadBDK() {
        File f = new File(fBDK);
        if (f.exists()) {
            listBDK = IOFile.doc(fBDK);
        } else {
            listBDK = new ArrayList<>();
        }
    }

    private void loadSV() {
        File f = new File(fSV);
        if (f.exists()) {
            listSV = IOFile.doc(fSV);
        } else {
            listSV = new ArrayList<>();
        }
    }

    private void loadMH() {
        File f = new File(fMH);
        if (f.exists()) {
            listMH = IOFile.doc(fMH);
        } else {
            listMH = new ArrayList<>();
        }
    }

    private void showMH(List<MonHoc> list) {
        tmMH.setRowCount(0);
        for (MonHoc monHoc : list) {
            tmMH.addRow(monHoc.toObjects());
        }
    }

    private void showSV(List<SinhVien> list) {
        tmSV.setRowCount(0);
        for (SinhVien sinhVien : list) {
            tmSV.addRow(sinhVien.toObjects());
        }
    }

    private void showBDK(List<BangDangKy> list) {
        tmBDK.setRowCount(0);
        for (BangDangKy bangDangKy : list) {
            tmBDK.addRow(bangDangKy.toObjects());
        }
    }

    private void ButtonState1(boolean b) {
        btThem1.setEnabled(b);
        btSua1.setEnabled(b);
        btCapnhat1.setEnabled(!b);
        btBoqua1.setEnabled(!b);
    }

    private void ButtonState2(boolean b) {
        btThem2.setEnabled(b);
        btSua2.setEnabled(b);
        btCapnhat2.setEnabled(!b);
        btBoqua2.setEnabled(!b);
    }

    private void ButtonState3(boolean b) {
        btThem3.setEnabled(b);
        btCapnhat3.setEnabled(!b);
        btBoqua3.setEnabled(!b);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btThem1 = new javax.swing.JButton();
        btSua1 = new javax.swing.JButton();
        btXoa1 = new javax.swing.JButton();
        btCapnhat1 = new javax.swing.JButton();
        btBoqua1 = new javax.swing.JButton();
        btHienthi1 = new javax.swing.JButton();
        btGhiFile = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        btThem2 = new javax.swing.JButton();
        btCapnhat2 = new javax.swing.JButton();
        btBoqua2 = new javax.swing.JButton();
        btSua2 = new javax.swing.JButton();
        btXoa2 = new javax.swing.JButton();
        btGhifile2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        textTimkiem = new javax.swing.JTextField();
        btTimkiem = new javax.swing.JButton();
        btHienthi2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        btThem3 = new javax.swing.JButton();
        btXoa3 = new javax.swing.JButton();
        btCapnhat3 = new javax.swing.JButton();
        btBoqua3 = new javax.swing.JButton();
        btLuufile3 = new javax.swing.JButton();
        btHienthi3 = new javax.swing.JButton();
        btSapxep3 = new javax.swing.JRadioButton();
        btSxTheoTen3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ma");

        jLabel2.setText("Ten mon hoc");

        jLabel3.setText("So luong tiet");

        jLabel4.setText("Loai");

        jTextField1.setEditable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dai cuong", "Co so nganh", "Chuyen nganh bat buoc", "Chuyen nganh tu chon" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jComboBox1, 0, 168, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btThem1.setText("Them");
        btThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThem1ActionPerformed(evt);
            }
        });

        btSua1.setText("Sua");
        btSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSua1ActionPerformed(evt);
            }
        });

        btXoa1.setText("Xoa");
        btXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoa1ActionPerformed(evt);
            }
        });

        btCapnhat1.setText("Cap nhat");
        btCapnhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapnhat1ActionPerformed(evt);
            }
        });

        btBoqua1.setText("Bo qua");
        btBoqua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBoqua1ActionPerformed(evt);
            }
        });

        btHienthi1.setText("Hien thi");
        btHienthi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienthi1ActionPerformed(evt);
            }
        });

        btGhiFile.setText("Luu vao file");
        btGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGhiFileActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Sap xep theo ten mon hoc");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Sap xep theo so tiet");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btThem1)
                            .addComponent(btCapnhat1))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btSua1)
                                .addGap(92, 92, 92)
                                .addComponent(btXoa1)
                                .addGap(64, 64, 64)
                                .addComponent(btHienthi1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btBoqua1)
                                .addGap(68, 68, 68)
                                .addComponent(btGhiFile)
                                .addGap(59, 59, 59)
                                .addComponent(jRadioButton1)
                                .addGap(28, 28, 28)
                                .addComponent(jRadioButton2)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem1)
                    .addComponent(btSua1)
                    .addComponent(btXoa1)
                    .addComponent(btHienthi1))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCapnhat1)
                    .addComponent(btBoqua1)
                    .addComponent(btGhiFile)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin Mon hoc", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("Ma Sinh Vien");

        jLabel6.setText("Ten");

        jLabel7.setText("Dia chi");

        jLabel8.setText("Dien thoai");

        jTextField4.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField4)
                    .addComponent(jTextField5)
                    .addComponent(jTextField6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(jLabel7))
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btThem2.setText("Them");
        btThem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThem2ActionPerformed(evt);
            }
        });

        btCapnhat2.setText("Cap nhat");
        btCapnhat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapnhat2ActionPerformed(evt);
            }
        });

        btBoqua2.setText("Bo qua");
        btBoqua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBoqua2ActionPerformed(evt);
            }
        });

        btSua2.setText("Sua");
        btSua2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSua2ActionPerformed(evt);
            }
        });

        btXoa2.setText("Xoa");
        btXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoa2ActionPerformed(evt);
            }
        });

        btGhifile2.setText("Luu vao file");
        btGhifile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGhifile2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Tim kiem sinh vien theo ten");

        btTimkiem.setText("Tim");
        btTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimkiemActionPerformed(evt);
            }
        });

        btHienthi2.setText("Hien thi");
        btHienthi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienthi2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btCapnhat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btThem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBoqua2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSua2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btGhifile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btXoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(textTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(btTimkiem))
                            .addComponent(btHienthi2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem2)
                    .addComponent(btSua2)
                    .addComponent(btXoa2)
                    .addComponent(jLabel9)
                    .addComponent(textTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTimkiem))
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCapnhat2)
                    .addComponent(btBoqua2)
                    .addComponent(btGhifile2)
                    .addComponent(btHienthi2))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin sinh vien", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jLabel10.setText("Ma SV");

        jLabel11.setText("TenSV");

        jLabel12.setText("Ma MH");

        jLabel13.setText("Ten MH");

        jTextField9.setEditable(false);

        jTextField11.setEditable(false);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Thoi gian ");

        jTextField8.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField11)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btThem3.setText("Them Dang Ky");
        btThem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThem3ActionPerformed(evt);
            }
        });

        btXoa3.setText("Xoa Dang Ky");
        btXoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoa3ActionPerformed(evt);
            }
        });

        btCapnhat3.setText("Cap nhat");
        btCapnhat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapnhat3ActionPerformed(evt);
            }
        });

        btBoqua3.setText("Bo qua");
        btBoqua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBoqua3ActionPerformed(evt);
            }
        });

        btLuufile3.setText("Luu vao file");
        btLuufile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuufile3ActionPerformed(evt);
            }
        });

        btHienthi3.setText("Hien thi");
        btHienthi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHienthi3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(btSapxep3);
        btSapxep3.setText("Sap xep theo ngay dang ky");

        buttonGroup2.add(btSxTheoTen3);
        btSxTheoTen3.setSelected(true);
        btSxTheoTen3.setText("Sap xep theo ten sinh vien");
        btSxTheoTen3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSxTheoTen3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btThem3)
                            .addComponent(btCapnhat3))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBoqua3)
                            .addComponent(btXoa3))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btLuufile3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btHienthi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSxTheoTen3)
                            .addComponent(btSapxep3))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem3)
                    .addComponent(btXoa3)
                    .addComponent(btHienthi3))
                .addGap(27, 27, 27)
                .addComponent(btSxTheoTen3)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCapnhat3)
                    .addComponent(btBoqua3)
                    .addComponent(btLuufile3)
                    .addComponent(btSapxep3))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bang Dang Ky", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        listMH.sort(new Comparator<MonHoc>() {
            @Override
            public int compare(MonHoc o1, MonHoc o2) {
                return o1.getTongSoTiet() - o2.getTongSoTiet();
            }
        });
        showMH(listMH);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThem1ActionPerformed
        ButtonState1(false);
        them = true;
        int n = listMH.size();
        if (n > 0) {
            int max = -1;
            for (MonHoc monHoc : listMH) {
                if (monHoc.getMa() > max) {
                    max = monHoc.getMa();
                }
            }
            MonHoc.setIma(max + 1);
        }
        jTextField1.setText(MonHoc.getIma() + "");
        jTextField2.requestFocus();
    }//GEN-LAST:event_btThem1ActionPerformed

    private void btCapnhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapnhat1ActionPerformed
        if (them) {
            try {
                String ten = jTextField2.getText();
                String st = jTextField3.getText();
                if (ten.isEmpty() || st.isEmpty()) {
                    throw new TrongException();
                }
                int soTiet = Integer.parseInt(st);
                String loai = jComboBox1.getSelectedItem().toString();
                MonHoc m = new MonHoc(ten, soTiet, loai);
                tmMH.addRow(m.toObjects());
                listMH.add(m);
                showMH(listMH);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jComboBox1.setSelectedIndex(0);
                them = false;
                ButtonState1(true);
                return;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui long nhap so");
                jTextField3.requestFocus();
                return;
            } catch (TrongException e) {
                JOptionPane.showMessageDialog(this, "Khong duoc de trong!");
                if (jTextField2.getText().isEmpty()) {
                    jTextField2.requestFocus();
                } else {
                    jTextField3.requestFocus();
                }
                return;
            }
        }

        if (sua) {
            int row = jTable1.getSelectedRow();
            if (row >= 0 && row <= jTable1.getRowCount() - 1) {
                jTextField2.requestFocus();
                try {
                    String ten = jTextField2.getText();
                    String st = jTextField3.getText();
                    if (ten.isEmpty() || st.isEmpty()) {
                        throw new TrongException();
                    }
                    int soTiet = Integer.parseInt(st);
                    String loai = jComboBox1.getSelectedItem().toString();
                    tmMH.setValueAt(ten, row, 1);
                    tmMH.setValueAt(st, row, 2);
                    tmMH.setValueAt(loai, row, 3);
                    int ma = Integer.parseInt(jTextField1.getText());
                    MonHoc m = new MonHoc(ma, ten, soTiet, loai);
                    listMH.set(row, m);
                    //showMH(listMH);
                    ButtonState1(true);
                    sua = false;
                    jTextField1.setText("");
                    jTextField2.setText("");
                    jTextField3.setText("");
                    jComboBox1.setSelectedIndex(0);
                } catch (TrongException e) {
                    JOptionPane.showMessageDialog(this, "Khong duoc de trong!");
                    if (jTextField2.getText().isEmpty()) {
                        jTextField2.requestFocus();
                    } else {
                        jTextField3.requestFocus();
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Vui long nhap so");
                    jTextField3.requestFocus();
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui long chon mon hoc de xoa!");
                return;
            }
        }
    }//GEN-LAST:event_btCapnhat1ActionPerformed

    private void btBoqua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBoqua1ActionPerformed
        ButtonState1(true);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        them = false;
        sua = false;
    }//GEN-LAST:event_btBoqua1ActionPerformed

    private void btSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSua1ActionPerformed
        ButtonState1(false);
        sua = true;
    }//GEN-LAST:event_btSua1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        jTextField1.setText(tmMH.getValueAt(row, 0).toString());
        jTextField2.setText(tmMH.getValueAt(row, 1).toString());
        jTextField3.setText(tmMH.getValueAt(row, 2).toString());
        jComboBox1.setSelectedItem(tmMH.getValueAt(row, 3));
    }//GEN-LAST:event_jTable1MouseClicked

    private void btGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGhiFileActionPerformed
        IOFile.ghi(fMH, listMH);
    }//GEN-LAST:event_btGhiFileActionPerformed

    private void btHienthi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienthi1ActionPerformed
        showMH(listMH);
    }//GEN-LAST:event_btHienthi1ActionPerformed

    private void btXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoa1ActionPerformed
        int row = jTable1.getSelectedRow();
        if (row >= 0 && row <= jTable1.getRowCount() - 1) {
            if (JOptionPane.showConfirmDialog(this, "Ban co chac chan xoa khong?", "Xoa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                tmMH.removeRow(row);
                listMH.remove(row);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jComboBox1.setSelectedIndex(0);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui long chon mon hoc de xoa!");
            return;
        }
    }//GEN-LAST:event_btXoa1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        listMH.sort(new Comparator<MonHoc>() {
            @Override
            public int compare(MonHoc o1, MonHoc o2) {
                return o1.getTen().toLowerCase().compareTo(o2.getTen().toLowerCase());
            }
        });
        showMH(listMH);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btThem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThem2ActionPerformed
        ButtonState2(false);
        them2 = true;
        int n = listSV.size();
        if (n >= 1) {
            int max = -1;
            for (SinhVien sinhVien : listSV) {
                if (sinhVien.getMa() > max) {
                    max = sinhVien.getMa();
                }
            }
            SinhVien.setIma(max + 1);
        }
        jTextField4.setText(SinhVien.getIma() + "");
        jTextField5.requestFocus();
    }//GEN-LAST:event_btThem2ActionPerformed

    private void btCapnhat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapnhat2ActionPerformed
        if (them2) {
            try {
                String ten, diaChi, dthoai;
                ten = jTextField5.getText();
                diaChi = jTextField6.getText();
                dthoai = jTextField7.getText();
                if (ten.isEmpty() || diaChi.isEmpty() || dthoai.isEmpty()) {
                    throw new TrongException();
                }
                if (!dthoai.matches("^\\d+$")) {
                    throw new Dienthoai();
                }
                SinhVien d = new SinhVien(ten, diaChi, dthoai);
                listSV.add(d);
                tmSV.addRow(d.toObjects());
                ButtonState2(true);
                them2 = false;
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                return;
            } catch (TrongException e) {
                JOptionPane.showMessageDialog(this, "Khong duoc bo trong!");
                if (jTextField5.getText().isEmpty()) {
                    jTextField5.requestFocus();
                } else if (jTextField6.getText().isEmpty()) {
                    jTextField6.requestFocus();
                } else {
                    jTextField7.requestFocus();
                }
                return;
            } catch (Dienthoai e) {
                JOptionPane.showMessageDialog(this, "Vui long nhap so!");
                jTextField7.requestFocus();
                return;
            }
        }
        if (sua2) {
            int row = jTable2.getSelectedRow();
            if (row >= 0 && row <= jTable2.getRowCount() - 1) {
                try {
                    String ten, diaChi, dthoai;
                    ten = jTextField5.getText();
                    diaChi = jTextField6.getText();
                    dthoai = jTextField7.getText();
                    if (ten.isEmpty() || diaChi.isEmpty() || dthoai.isEmpty()) {
                        throw new TrongException();
                    }
                    if (!dthoai.matches("^\\d+$")) {
                        throw new Dienthoai();
                    }
                    int ma = Integer.parseInt(jTextField4.getText());
                    SinhVien d = new SinhVien(ma, ten, diaChi, dthoai);
                    tmSV.setValueAt(ten, row, 1);
                    tmSV.setValueAt(diaChi, row, 2);
                    tmSV.setValueAt(dthoai, row, 3);
                    listSV.set(row, d);
                    showSV(listSV);
                    ButtonState2(true);
                    sua2 = false;
                    jTextField4.setText("");
                    jTextField5.setText("");
                    jTextField6.setText("");
                    jTextField7.setText("");

                } catch (TrongException e) {
                    JOptionPane.showMessageDialog(this, "Khong duoc bo trong!");
                    if (jTextField5.getText().isEmpty()) {
                        jTextField5.requestFocus();
                    } else if (jTextField6.getText().isEmpty()) {
                        jTextField6.requestFocus();
                    } else {
                        jTextField7.requestFocus();
                    }
                    return;
                } catch (Dienthoai e) {
                    JOptionPane.showMessageDialog(this, "Vui long nhap so!");
                    jTextField7.requestFocus();
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui long chon de sua!");
                return;
            }
        }
    }//GEN-LAST:event_btCapnhat2ActionPerformed

    private void btBoqua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBoqua2ActionPerformed
        ButtonState2(true);
        them2 = false;
        sua2 = false;
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
    }//GEN-LAST:event_btBoqua2ActionPerformed

    private void btSua2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSua2ActionPerformed
        sua2 = true;
        ButtonState2(false);
    }//GEN-LAST:event_btSua2ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();
        if (row >= 0 && row <= jTable2.getRowCount() - 1) {
            jTextField4.setText(tmSV.getValueAt(row, 0).toString());
            jTextField5.setText(tmSV.getValueAt(row, 1).toString());
            jTextField6.setText(tmSV.getValueAt(row, 2).toString());
            jTextField7.setText(tmSV.getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void btGhifile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGhifile2ActionPerformed
        IOFile.ghi(fSV, listSV);
    }//GEN-LAST:event_btGhifile2ActionPerformed

    private void btXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoa2ActionPerformed
        int row = jTable2.getSelectedRow();
        if (row >= 0 && row <= jTable2.getRowCount() - 1) {
            if (JOptionPane.showConfirmDialog(this, "Ban co chac chan xoa khong?", "Xoa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                tmSV.removeRow(row);
                listSV.remove(row);
                showSV(listSV);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Chon sinh vien de xoa!");
            return;
        }
    }//GEN-LAST:event_btXoa2ActionPerformed

    private void btHienthi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienthi2ActionPerformed
        showSV(listSV);
    }//GEN-LAST:event_btHienthi2ActionPerformed

    private void btTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimkiemActionPerformed
        try {
            String temp = textTimkiem.getText().trim().toLowerCase();
            if (temp.isEmpty()) {
                throw new TrongException();
            }
            List<SinhVien> list = new ArrayList<>();
            for (SinhVien sinhVien : listSV) {
                if (sinhVien.getTen().toLowerCase().contains(temp)) {
                    list.add(sinhVien);
                }
            }
            showSV(list);
        } catch (TrongException e) {
            JOptionPane.showMessageDialog(this, "Vui long nhap thong tin sinh vien de tim!");
            textTimkiem.requestFocus();
        }
    }//GEN-LAST:event_btTimkiemActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void btLuufile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuufile3ActionPerformed
        IOFile.ghi(fBDK, listBDK);
    }//GEN-LAST:event_btLuufile3ActionPerformed

    private void btThem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThem3ActionPerformed
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        jTextField9.setText("");
        jTextField11.setText("");
        jTextField8.setText("");
        ButtonState3(false);
        List<SinhVien> sv = IOFile.doc(fSV);
        List<MonHoc> mh = IOFile.doc(fMH);
        for (SinhVien sinhVien : sv) {
            jComboBox2.addItem(sinhVien.getMa() + "");
        }
        for (MonHoc monHoc : mh) {
            jComboBox3.addItem(monHoc.getMa() + "");
        }
    }//GEN-LAST:event_btThem3ActionPerformed

    private void btCapnhat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapnhat3ActionPerformed
        List<SinhVien> sv = IOFile.doc(fSV);
        List<MonHoc> mh = IOFile.doc(fMH);
        for (SinhVien sinhVien : sv) {
            jComboBox2.addItem(sinhVien.getMa() + "");
        }
        for (MonHoc monHoc : mh) {
            jComboBox3.addItem(monHoc.getMa() + "");
        }
        try {
            int svma = Integer.parseInt(jComboBox2.getSelectedItem().toString());
            int mhma = Integer.parseInt(jComboBox3.getSelectedItem().toString());
            String tensv = null, tenmh = null;
            for (SinhVien sinhVien : sv) {
                if (sinhVien.getMa() == svma) {
                    jTextField9.setText(sinhVien.getTen());
                    tensv = sinhVien.getTen();
                    break;
                }
            }
            for (MonHoc monHoc : mh) {
                if (monHoc.getMa() == mhma) {
                    jTextField11.setText(monHoc.getTen());
                    tenmh = monHoc.getTen();
                    break;
                }
            }
            int count = 0;
            for (BangDangKy bangDangKy : listBDK) {
                if (bangDangKy.getMaSV() == svma) {
                    count++;
                    if (count > 8) {
                        throw new GioihanException();
                    }
                    if (bangDangKy.getMaMH() == mhma) {
                        throw new TrungException();
                    }
                }
            }
            Date d = new Date();
            SimpleDateFormat fomatter = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
            String thoiGian = fomatter.format(d);
            jTextField8.setText(thoiGian);
            BangDangKy b;
            b = new BangDangKy(svma, mhma, tensv, tenmh, thoiGian);
            listBDK.add(b);
            tmBDK.addRow(b.toObjects());
            ButtonState3(true);
            jComboBox3.removeAllItems();
            jComboBox2.removeAllItems();
            jTextField9.setText("");
            jTextField11.setText("");
            jTextField8.setText("");
        } catch (GioihanException e) {
            JOptionPane.showMessageDialog(this, "Sinh vien khong the dang ky qua 8 mon");
            
        } catch (TrungException e) {
            JOptionPane.showMessageDialog(this, "Sinh vien da dang ky mon hoc nay!");
        }


    }//GEN-LAST:event_btCapnhat3ActionPerformed

    private void btHienthi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHienthi3ActionPerformed
        showBDK(listBDK);
    }//GEN-LAST:event_btHienthi3ActionPerformed

    private void btBoqua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBoqua3ActionPerformed
        ButtonState3(true);
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
    }//GEN-LAST:event_btBoqua3ActionPerformed

    private void btXoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoa3ActionPerformed
        int row = jTable3.getSelectedRow();
        if (row >= 0 && row <= jTable3.getRowCount() - 1) {
            if (JOptionPane.showConfirmDialog(this, "Ban co chac chan xoa khong?", "Xoa", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                tmBDK.removeRow(row);
                listBDK.remove(row);
                showBDK(listBDK);
                jComboBox2.removeAllItems();
                jComboBox3.removeAllItems();
                jTextField9.setText("");
                jTextField11.setText("");
                jTextField8.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui long chon de xoa!");
        }
    }//GEN-LAST:event_btXoa3ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        jTextField9.setText("");
        jTextField11.setText("");
        jTextField8.setText("");
        int row = jTable3.getSelectedRow();
        int n = jTable3.getRowCount();
        if (row >= 0 && row <= n - 1) {
            jComboBox2.addItem(jTable3.getValueAt(row, 0).toString());
            jComboBox2.setSelectedIndex(0);
            jTextField9.setText(jTable3.getValueAt(row, 1).toString());
            jComboBox3.addItem(jTable3.getValueAt(row, 2).toString());
            jComboBox3.setSelectedIndex(0);
            jTextField11.setText(jTable3.getValueAt(row, 3).toString());
            jTextField8.setText(jTable3.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_jTable3MouseClicked

    private void btSxTheoTen3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSxTheoTen3ActionPerformed
        listBDK.sort(new Comparator<BangDangKy>() {
            @Override
            public int compare(BangDangKy o1, BangDangKy o2) {
                String[] name1 = o1.getTenSV().trim().toLowerCase().split("\\s+");
                String[] name2 = o2.getTenSV().trim().toLowerCase().split("\\s+");
                if (name1[name1.length-1].equals(name2[name2.length-1])) {
                    return o1.getTenSV().compareToIgnoreCase(o2.getTenSV());
                }
                else {
                    return name1[name1.length-1].compareTo(name2[name2.length-1]);
                }
            }
        });
        showBDK(listBDK);
    }//GEN-LAST:event_btSxTheoTen3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBoqua1;
    private javax.swing.JButton btBoqua2;
    private javax.swing.JButton btBoqua3;
    private javax.swing.JButton btCapnhat1;
    private javax.swing.JButton btCapnhat2;
    private javax.swing.JButton btCapnhat3;
    private javax.swing.JButton btGhiFile;
    private javax.swing.JButton btGhifile2;
    private javax.swing.JButton btHienthi1;
    private javax.swing.JButton btHienthi2;
    private javax.swing.JButton btHienthi3;
    private javax.swing.JButton btLuufile3;
    private javax.swing.JRadioButton btSapxep3;
    private javax.swing.JButton btSua1;
    private javax.swing.JButton btSua2;
    private javax.swing.JRadioButton btSxTheoTen3;
    private javax.swing.JButton btThem1;
    private javax.swing.JButton btThem2;
    private javax.swing.JButton btThem3;
    private javax.swing.JButton btTimkiem;
    private javax.swing.JButton btXoa1;
    private javax.swing.JButton btXoa2;
    private javax.swing.JButton btXoa3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField textTimkiem;
    // End of variables declaration//GEN-END:variables
}
